/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myinterface from './interface/index.js';
export { ProtectedDataSharing__factory } from './ProtectedDataSharing__factory.js';
