pipeline:
  test_node16:
    image: node:16
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  test_node14:
    image: node:14
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  npm_publish:
    image: plugins/npm
    secrets: [npm_token]
    username: iexecteam
    email: dev@iex.ec
    tag: latest
    when:
      ref: [refs/tags/v*]
