/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollection } from "./ICollection.js";
export type { IExecPocoDelegate } from "./IExecPocoDelegate.js";
export type { IProtectedDataSharing } from "./IProtectedDataSharing.js";
export type { IRegistry } from "./IRegistry.js";
export type { IRental } from "./IRental.js";
export type { ISale } from "./ISale.js";
export type { ISubscription } from "./ISubscription.js";
