/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myinterface from './interface/index.js';
export type { myinterface };
export type { ProtectedDataSharing } from './ProtectedDataSharing.js';
export * as factories from './factories/index.js';
export type { ICollection } from './interface/ICollection.js';
export { ICollection__factory } from './factories/interface/ICollection__factory.js';
export type { IExecPocoDelegate } from './interface/IExecPocoDelegate.js';
export { IExecPocoDelegate__factory } from './factories/interface/IExecPocoDelegate__factory.js';
export type { IProtectedDataSharing } from './interface/IProtectedDataSharing.js';
export { IProtectedDataSharing__factory } from './factories/interface/IProtectedDataSharing__factory.js';
export type { IRegistry } from './interface/IRegistry.js';
export { IRegistry__factory } from './factories/interface/IRegistry__factory.js';
export type { IRental } from './interface/IRental.js';
export { IRental__factory } from './factories/interface/IRental__factory.js';
export type { ISale } from './interface/ISale.js';
export { ISale__factory } from './factories/interface/ISale__factory.js';
export type { ISubscription } from './interface/ISubscription.js';
export { ISubscription__factory } from './factories/interface/ISubscription__factory.js';
export { ProtectedDataSharing__factory } from './factories/ProtectedDataSharing__factory.js';
