name: Publish Package NPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag to publish (latest or nightly)'
        required: true
        type: choice
        options:
          - latest
          - nightly
        default: nightly # Check this with the team

jobs:
  publish-npm:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.0.0
    with:
      scope: '@iexec/deserializer'
      registry: 'https://registry.npmjs.org'
      node-version: '18'
      environment: ${{ inputs.tag == 'latest' ? 'production' : 'staging' }}
      working-directory: "packages/dataprotector-deserializer"
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
