/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common.js';

export interface AppWhitelistInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'addApp'
      | 'initialize'
      | 'isRegistered'
      | 'keyHasPurpose'
      | 'owner'
      | 'renounceOwnership'
      | 'transferOwnership'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'Initialized'
      | 'NewAppAddedToAppWhitelist'
      | 'OwnershipTransferred'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'addApp', values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'isRegistered',
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'keyHasPurpose',
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: 'addApp', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isRegistered',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'keyHasPurpose',
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewAppAddedToAppWhitelistEvent {
  export type InputTuple = [appAddress: AddressLike];
  export type OutputTuple = [appAddress: string];
  export interface OutputObject {
    appAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AppWhitelist extends BaseContract {
  connect(runner?: ContractRunner | null): AppWhitelist;
  waitForDeployment(): Promise<this>;

  interface: AppWhitelistInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addApp: TypedContractMethod<[_app: AddressLike], [void], 'nonpayable'>;

  initialize: TypedContractMethod<
    [initialOwner: AddressLike],
    [void],
    'nonpayable'
  >;

  isRegistered: TypedContractMethod<[_app: AddressLike], [boolean], 'view'>;

  keyHasPurpose: TypedContractMethod<
    [key: BytesLike, purpose: BigNumberish],
    [boolean],
    'view'
  >;

  owner: TypedContractMethod<[], [string], 'view'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: 'addApp'
  ): TypedContractMethod<[_app: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'initialize'
  ): TypedContractMethod<[initialOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'isRegistered'
  ): TypedContractMethod<[_app: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'keyHasPurpose'
  ): TypedContractMethod<
    [key: BytesLike, purpose: BigNumberish],
    [boolean],
    'view'
  >;
  getFunction(
    nameOrSignature: 'owner'
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'renounceOwnership'
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  getEvent(
    key: 'Initialized'
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: 'NewAppAddedToAppWhitelist'
  ): TypedContractEvent<
    NewAppAddedToAppWhitelistEvent.InputTuple,
    NewAppAddedToAppWhitelistEvent.OutputTuple,
    NewAppAddedToAppWhitelistEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    'Initialized(uint64)': TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    'NewAppAddedToAppWhitelist(address)': TypedContractEvent<
      NewAppAddedToAppWhitelistEvent.InputTuple,
      NewAppAddedToAppWhitelistEvent.OutputTuple,
      NewAppAddedToAppWhitelistEvent.OutputObject
    >;
    NewAppAddedToAppWhitelist: TypedContractEvent<
      NewAppAddedToAppWhitelistEvent.InputTuple,
      NewAppAddedToAppWhitelistEvent.OutputTuple,
      NewAppAddedToAppWhitelistEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
