###################### DATAPROTECTOR DESERIALIZER DRONE CI ######################
kind: pipeline
type: docker
name: dataprotector-deserializer-default

trigger:
  event: push

steps:
  - name: build test dependency dataprotector-sdk
    image: node:18
    pull: always
    commands:
      - cd packages/sdk
      - npm ci
      - npm run codegen
      - npm run build

  - name: install
    image: node:18
    pull: always
    commands:
      - cd packages/dataprotector-deserializer
      - node -v
      - npm -v
      - npm ci
      - npm run test:prepare

  - name: format
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm run check-format

  - name: lint
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm run lint

  - name: check-types
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm run check-types

  - name: test
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm run test

  - name: build
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm run build

---
kind: pipeline
type: docker
name: dataprotector-deserializer publish dry-run

trigger:
  event: push

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - cd packages/dataprotector-deserializer
      - npm ci

  - name: build
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm run build

  - name: npm publish dry-run
    image: node:18
    commands:
      - cd packages/dataprotector-deserializer
      - npm publish --dry-run
