kind: pipeline
type: docker
name: default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: install deps
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    pull: always
    commands:
      - node -v
      - npm -v
      - cd Smart_Contract
      - npm ci

  - name: check format
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run check-format

  - name: check lint
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run lint

  - name: compile smart contracts
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run compile

  - name: test smart contracts
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run test

  - name: dry-deployment smart-contract
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run deploy
      - cat .smart-contract-address

---
# deploy smart contract in prod or dev
kind: pipeline
type: docker
name: deploy smart contract

trigger:
  event:
    - promote
  target:
    - smart-contract-dev
    - smart-contract-production
  branch:
    - develop
    - main

steps:
  - name: install deps
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    pull: always
    commands:
      - node -v
      - npm -v
      - cd Smart_Contract
      - npm ci

  - name: check format
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run check-format

  - name: check lint
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run lint

  - name: compile smart contracts
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run compile

  - name: test smart contracts
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run test

  - name: smart-contract dev deployment
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-dev-privatekey
    commands:
      - cd Smart_Contract
      - npm run deploy -- --network bellecour
      - cat .smart-contract-address
    when:
      target:
        - smart-contract-dev
      branch:
        - develop

  - name: smart-contract prod deployment
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-prod-privatekey
    commands:
      - cd Smart_Contract
      - npm run deploy -- --network bellecour
      - cat .smart-contract-address
    when:
      target:
        - smart-contract-production
      branch:
        - main

  # TODO: Adapt/delete this verification step according with the new dev environment
  - name: verify dev contract
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run verify -- --network bellecour $(cat .smart-contract-address) $(cat .constructor-args-params)
    when:
      target:
        - smart-contract-dev
      branch:
        - develop

  - name: verify prod contract
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - cd Smart_Contract
      - npm run verify -- --network bellecour $(cat .smart-contract-address) $(cat .constructor-args-params)
    when:
      target:
        - smart-contract-production
      branch:
        - main
# TODO: add a last step to add the dev ens or prod ens on the deployed SC address
