/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProtectedDataSharing,
  IProtectedDataSharingInterface,
} from "../../interfaces/IProtectedDataSharing.js";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "appAddress",
        type: "address",
      },
    ],
    name: "AppNotOwnByContract",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
    ],
    name: "CollectionNotEmpty",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint48",
        name: "_duration",
        type: "uint48",
      },
    ],
    name: "DurationInvalide",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "NoProtectedDataInCollection",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
    ],
    name: "NoSubscriptionParams",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "protectedDatas",
        type: "address",
      },
    ],
    name: "NoValidRentalOrSubscription",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
    ],
    name: "NotCollectionOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
    ],
    name: "OnGoingCollectionSubscriptions",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "ProctedDataInSubscription",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataAvailableForRenting",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataAvailableInSubscription",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataCurrentlyBeingRented",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataForSale",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataNotAvailableForRenting",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataNotForSale",
    type: "error",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "workerpool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "workerpoolprice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tag",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "category",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "trust",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "apprestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "datasetrestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "requesterrestrict",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.WorkerpoolOrder",
        name: "workerpoolOrder",
        type: "tuple",
      },
    ],
    name: "WorkerpoolOrderNotFree",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "expectedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "receivedAmount",
        type: "uint256",
      },
    ],
    name: "WrongAmountSent",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "renter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "endDate",
        type: "uint48",
      },
    ],
    name: "NewRental",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "subscriber",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "endDate",
        type: "uint48",
      },
    ],
    name: "NewSubscription",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint112",
            name: "price",
            type: "uint112",
          },
          {
            internalType: "uint48",
            name: "duration",
            type: "uint48",
          },
        ],
        indexed: false,
        internalType: "struct ISubscription.SubscriptionParams",
        name: "subscriptionParams",
        type: "tuple",
      },
    ],
    name: "NewSubscriptionParams",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint112",
        name: "price",
        type: "uint112",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "duration",
        type: "uint48",
      },
    ],
    name: "ProtectedDataAddedForRenting",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint112",
        name: "price",
        type: "uint112",
      },
    ],
    name: "ProtectedDataAddedForSale",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataAddedForSubscription",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "dealId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum IProtectedDataSharing.mode",
        name: "mode",
        type: "uint8",
      },
    ],
    name: "ProtectedDataConsumed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataRemovedFromRenting",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataRemovedFromSale",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataRemovedFromSubscription",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collectionTokenIdFrom",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
    ],
    name: "ProtectedDataSold",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "protectedData",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newCollection",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldCollection",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "appAddress",
        type: "address",
      },
    ],
    name: "ProtectedDataTransfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
      {
        internalType: "address",
        name: "_appAddress",
        type: "address",
      },
    ],
    name: "addProtectedDataToCollection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenIdFrom",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "buyProtectedData",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenIdFrom",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_collectionTokenIdTo",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_appAddress",
        type: "address",
      },
    ],
    name: "buyProtectedDataForCollection",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "workerpool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "workerpoolprice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tag",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "category",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "trust",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "apprestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "datasetrestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "requesterrestrict",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.WorkerpoolOrder",
        name: "_workerpoolOrder",
        type: "tuple",
      },
      {
        internalType: "string",
        name: "_contentPath",
        type: "string",
      },
    ],
    name: "consumeProtectedData",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "createCollection",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
    ],
    name: "removeCollection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "removeProtectedDataForSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "removeProtectedDataFromCollection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "removeProtectedDataFromRenting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "removeProtectedDataFromSubscription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "rentProtectedData",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
      {
        internalType: "uint112",
        name: "_price",
        type: "uint112",
      },
    ],
    name: "setProtectedDataForSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
      {
        internalType: "uint112",
        name: "_price",
        type: "uint112",
      },
      {
        internalType: "uint48",
        name: "_duration",
        type: "uint48",
      },
    ],
    name: "setProtectedDataToRenting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_protectedData",
        type: "address",
      },
    ],
    name: "setProtectedDataToSubscription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint112",
            name: "price",
            type: "uint112",
          },
          {
            internalType: "uint48",
            name: "duration",
            type: "uint48",
          },
        ],
        internalType: "struct ISubscription.SubscriptionParams",
        name: "_subscriptionParams",
        type: "tuple",
      },
    ],
    name: "setSubscriptionParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collectionTokenId",
        type: "uint256",
      },
    ],
    name: "subscribeTo",
    outputs: [
      {
        internalType: "uint256",
        name: "endDate",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IProtectedDataSharing__factory {
  static readonly abi = _abi;
  static createInterface(): IProtectedDataSharingInterface {
    return new Interface(_abi) as IProtectedDataSharingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProtectedDataSharing {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IProtectedDataSharing;
  }
}
