###################### SUBGRAPH DRONE CI ######################
kind: pipeline
type: docker
name: subgraph-default

trigger:
  event: push

steps:
  - name: build-subgraph
    image: node:18.19
    environment:
      ENV: prod
    commands:
      - cd packages/subgraph
      - npm ci
      - npm run codegen
      - npm run build
      - npm run check-format
