###################### SUBGRAPH DRONE CI ######################
kind: pipeline
type: docker
name: subgraph-default

trigger:
  event: push

steps:
  - name: only subgraph package
    image: bash
    commands:
      - cp -r packages/subgraph/. . && rm -rf packages

  - name: build-subgraph
    image: node:18.19
    commands:
      - npm ci
      - npm run codegen
      - npm run build
