###################### SHARING SMART CONTRACT DRONE CI ######################
kind: pipeline
type: docker
name: sharing-smart-contract-default

trigger:
  event: push

steps:
  - name: install-deps
    image: node:18.19
    pull: always
    commands:
      - cd packages/sharing-smart-contract
      - node -v
      - npm -v
      - npm ci

  - name: install-forge
    image: node:18.19
    pull: always
    commands:
      - export XDG_CONFIG_HOME=/drone/src
      - curl -L https://foundry.paradigm.xyz | bash
      - export PATH="$PATH:/drone/src/.foundry/bin"
      - foundryup
      - cd packages/sharing-smart-contract
      - forge install foundry-rs/forge-std --no-git

  - name: bellecour-fork
    detach: true
    image: ghcr.io/foundry-rs/foundry:latest
    pull: always
    expose:
      - 8545
    commands:
      - anvil --host 0.0.0.0 --port 8545 --hardfork berlin --fork-url https://bellecour.iex.ec --chain-id 134 --gas-limit 6700000 --gas-price 0

  - name: bellecour-fork-healthy
    image: bash
    commands:
      - while ! nc -z bellecour-fork 8545 ; do sleep 1 ; done && echo "bellecour-fork ready"
    depends_on:
      - bellecour-fork

  - name: bellecour-fork-voucher-deployment
    #  https://github.com/iExecBlockchainComputing/voucher-deployer
    image: pierreiexec/voucher-deployer
    pull: always
    environment:
      RPC_URL: http://bellecour-fork:8545
      SKIP_SUBGRAPH: 'true'
    commands:
      - sh /app/entrypoint.sh
      - echo "VOUCHER_HUB_ADDRESS=$(cat /app/out/VoucherHub.address)" >> ./packages/sharing-smart-contract/.env
      - echo "export const VOUCHER_HUB_ADDRESS = '$(cat /app/out/VoucherHub.address)';" > ./packages/sharing-smart-contract/test/bellecour-fork/voucher-config.js
    depends_on:
      - install-deps
      - install-forge
      - bellecour-fork-healthy

  - name: compile
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - export PATH="$PATH:/drone/src/.foundry/bin"
      - npm run compile
    depends_on:
      - install-forge
      - install-deps

  - name: check format
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - npm run check-format
    depends_on:
      - install-deps

  - name: lint
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - npm run lint
    depends_on:
      - install-deps

  - name: uml-diagrams
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - npm run uml
    depends_on:
      - install-deps

  - name: static-analyzer
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - git clone https://github.com/Picodes/4naly3er.git
      - cd 4naly3er
      - git reset --hard HEAD~1 # FIX issue https://github.com/Picodes/4naly3er/issues/48
      - yarn install
      - yarn analyze ../contracts
    depends_on:
      - lint

  - name: hardhat-tests
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - export PATH="$PATH:/drone/src/.foundry/bin"
      - npm run test -- --network ci-bellecour-fork
    depends_on:
      - install-deps
      - install-forge
      - compile
      - bellecour-fork-healthy
      - bellecour-fork-voucher-deployment

  - name: upgrade-test
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - export PATH="$PATH:/drone/src/.foundry/bin"
      - npm run upgrade-local-fork -- --network ci-bellecour-fork
    depends_on:
      - install-deps
      - install-forge
      - compile
      - bellecour-fork-healthy
      - bellecour-fork-voucher-deployment

  - name: forge-tests
    image: node:18.19
    commands:
      - cd packages/sharing-smart-contract
      - export PATH="$PATH:/drone/src/.foundry/bin"
      - forge test --no-match-test "invariant" -vvvv
    depends_on:
      - install-deps
      - install-forge
      - compile
      - bellecour-fork-healthy
      - bellecour-fork-voucher-deployment
