---
#pipeline to publish dapp contract on iexec
kind: pipeline
type: docker
name: deploy-dapp-contract

trigger:
  event:
    - promote
  target:
    - dapp-dev
    - dapp-prod
  # branch:
  #   - develop
  #   - v2
  #   - main

steps:
  - name: only dapp package
    image: bash
    commands:
      - cp -r packages/deployment-dapp/. . && rm -rf packages

  - name: get scone fingerprint (dev)
    image: iexechub/protected-data-delivery-dapp:dev-${DRONE_COMMIT}-sconify-5.7.5-v12-production
    commands:
      - SCONE_HASH=1 node > deployment-dapp/.scone-fingerprint
    when:
      target:
        - dapp-dev
      # branch:
      #   - v2
      #   - develop

  - name: get scone fingerprint (prod)
    # /!\: maintain the version here
    image: iexechub/protected-data-delivery-dapp:0.0.1-sconify-5.7.5-v12-production
    commands:
      - SCONE_HASH=1 node > deployment-dapp/.scone-fingerprint
    when:
      target:
        - dapp-prod
      branch:
        - main

  - name: format
    image: node:18.19
    commands:
      - npm run check-format

  - name: lint
    image: node:18.19
    commands:
      - npm run lint

  - name: install deps
    image: node:18.19
    pull: always
    commands:
      - npm ci

  - name: deploy dapp contract
    image: node:18.19
    pull: always
    environment:
      DRONE_DEPLOY_TO: $DRONE_DEPLOY_TO
      WALLET_PRIVATE_KEY_DEV:
        from_secret: protected-data-delivery-dapp-dev-privatekey
      WALLET_PRIVATE_KEY_PROD:
        from_secret: protected-data-delivery-dapp-prod-privatekey
    commands:
      - npm run deploy-dapp

  - name: configure ENS
    image: node:18.19
    pull: always
    environment:
      DRONE_DEPLOY_TO: $DRONE_DEPLOY_TO
      WALLET_PRIVATE_KEY_DEV:
        from_secret: protected-data-delivery-dapp-dev-privatekey
      WALLET_PRIVATE_KEY_PROD:
        from_secret: protected-data-delivery-dapp-prod-privatekey
    commands:
      - npm run configure-ens

  - name: publish-free-sell-order
    image: node:18
    environment:
      DRONE_DEPLOY_TO: $DRONE_DEPLOY_TO
      WALLET_PRIVATE_KEY_DEV:
        from_secret: protected-data-delivery-dapp-dev-privatekey
      WALLET_PRIVATE_KEY_PROD:
        from_secret: protected-data-delivery-dapp-prod-privatekey
      PRICE: '0'
      VOLUME: '1000000000'
    commands:
      - npm run publish-sell-order
      
---
# pipeline to transfer ownership of the dapp to the contract
kind: pipeline
type: docker
name: transfer-ownership

trigger:
  event:
    - promote
  target:
    - dapp-transfer-ownership-dev
    - dapp-transfer-ownership-prod
  branch:
    - develop
    - v2
    - main

steps:
  - name: only deployment-dapp package
    image: bash
    commands:
      - cp -r packages/deployment-dapp/. . && rm -rf packages

  - name: install-dependencies
    image: node:18
    pull: always
    commands:
      - npm ci

  - name: transfer-ownership
    image: node:18
    pull: always
    params:
      - DAPP_ADDRESS
      - NEW_OWNER
    environment:
      DRONE_DEPLOY_TO: $DRONE_DEPLOY_TO
      WALLET_PRIVATE_KEY_DEV:
        from_secret: protected-data-delivery-dapp-dev-privatekey
      WALLET_PRIVATE_KEY_PROD:
        from_secret: protected-data-delivery-dapp-prod-privatekey
    commands:
      - npm run transfer-ownership
