/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExecPocoDelegate,
  IExecPocoDelegateInterface,
} from "../../interface/IExecPocoDelegate.js";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "app",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "appprice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "tag",
                type: "bytes32",
              },
              {
                internalType: "address",
                name: "datasetrestrict",
                type: "address",
              },
              {
                internalType: "address",
                name: "workerpoolrestrict",
                type: "address",
              },
              {
                internalType: "address",
                name: "requesterrestrict",
                type: "address",
              },
              {
                internalType: "bytes32",
                name: "salt",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "sign",
                type: "bytes",
              },
            ],
            internalType: "struct IexecLibOrders_v5.AppOrder",
            name: "order",
            type: "tuple",
          },
          {
            internalType: "enum IexecLibOrders_v5.OrderOperationEnum",
            name: "operation",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.AppOrderOperation",
        name: "operation",
        type: "tuple",
      },
    ],
    name: "manageAppOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "dataset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "datasetprice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "tag",
                type: "bytes32",
              },
              {
                internalType: "address",
                name: "apprestrict",
                type: "address",
              },
              {
                internalType: "address",
                name: "workerpoolrestrict",
                type: "address",
              },
              {
                internalType: "address",
                name: "requesterrestrict",
                type: "address",
              },
              {
                internalType: "bytes32",
                name: "salt",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "sign",
                type: "bytes",
              },
            ],
            internalType: "struct IexecLibOrders_v5.DatasetOrder",
            name: "order",
            type: "tuple",
          },
          {
            internalType: "enum IexecLibOrders_v5.OrderOperationEnum",
            name: "operation",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.DatasetOrderOperation",
        name: "operation",
        type: "tuple",
      },
    ],
    name: "manageDatasetOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "app",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "appmaxprice",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "dataset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "datasetmaxprice",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "workerpool",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "workerpoolmaxprice",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "requester",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "tag",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "category",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "trust",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "beneficiary",
                type: "address",
              },
              {
                internalType: "address",
                name: "callback",
                type: "address",
              },
              {
                internalType: "string",
                name: "params",
                type: "string",
              },
              {
                internalType: "bytes32",
                name: "salt",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "sign",
                type: "bytes",
              },
            ],
            internalType: "struct IexecLibOrders_v5.RequestOrder",
            name: "order",
            type: "tuple",
          },
          {
            internalType: "enum IexecLibOrders_v5.OrderOperationEnum",
            name: "operation",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.RequestOrderOperation",
        name: "operation",
        type: "tuple",
      },
    ],
    name: "manageRequestOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "workerpool",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "workerpoolprice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "tag",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "category",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "trust",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "apprestrict",
                type: "address",
              },
              {
                internalType: "address",
                name: "datasetrestrict",
                type: "address",
              },
              {
                internalType: "address",
                name: "requesterrestrict",
                type: "address",
              },
              {
                internalType: "bytes32",
                name: "salt",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "sign",
                type: "bytes",
              },
            ],
            internalType: "struct IexecLibOrders_v5.WorkerpoolOrder",
            name: "order",
            type: "tuple",
          },
          {
            internalType: "enum IexecLibOrders_v5.OrderOperationEnum",
            name: "operation",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.WorkerpoolOrderOperation",
        name: "operation",
        type: "tuple",
      },
    ],
    name: "manageWorkerpoolOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "app",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "appprice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tag",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "datasetrestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "workerpoolrestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "requesterrestrict",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.AppOrder",
        name: "appOrder",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "dataset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "datasetprice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tag",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "apprestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "workerpoolrestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "requesterrestrict",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.DatasetOrder",
        name: "datasetOrder",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "workerpool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "workerpoolprice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tag",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "category",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "trust",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "apprestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "datasetrestrict",
            type: "address",
          },
          {
            internalType: "address",
            name: "requesterrestrict",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.WorkerpoolOrder",
        name: "workerpoolOrder",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "app",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "appmaxprice",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "dataset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "datasetmaxprice",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "workerpool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "workerpoolmaxprice",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "requester",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tag",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "category",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "trust",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "beneficiary",
            type: "address",
          },
          {
            internalType: "address",
            name: "callback",
            type: "address",
          },
          {
            internalType: "string",
            name: "params",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "sign",
            type: "bytes",
          },
        ],
        internalType: "struct IexecLibOrders_v5.RequestOrder",
        name: "requestOrder",
        type: "tuple",
      },
    ],
    name: "matchOrders",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExecPocoDelegate__factory {
  static readonly abi = _abi;
  static createInterface(): IExecPocoDelegateInterface {
    return new Interface(_abi) as IExecPocoDelegateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IExecPocoDelegate {
    return new Contract(address, _abi, runner) as unknown as IExecPocoDelegate;
  }
}
