kind: pipeline
type: docker
name: content-creator-usecase-demo-preview

trigger:
  event: push
  branch:
    - feature/wip-on-usecase-demo2

steps:
  - name: node -v & npm -v
    image: node:18.19
    commands:
      - node -v
      - npm -v

  - name: Vercel deploy to preview
    image: node:18.19
    environment:
      VERCEL_ORG_ID: team_qEUZmPwX3J0FFDAk23fSvIlq
      VERCEL_PROJECT_ID: prj_EAcfrH7s20W5M9jE28AQheyiJsQM
      VERCEL_TOKEN:
        from_secret: cedric-vercel-token
    commands:
      - npm install --global vercel@canary
      - vercel pull --yes --environment=preview --scope i-exec --token $VERCEL_TOKEN
      - VITE_APP_COMMIT=${DRONE_COMMIT} vercel build --scope i-exec --token $VERCEL_TOKEN
      - vercel deploy --prebuilt --scope i-exec --token $VERCEL_TOKEN
