#!/bin/sh

SUBGRAPH_PATH="packages/subgraph"
SDK_PATH="packages/sdk"
ROOT_DIR=$(pwd)

# Check if it was a branch checkout
if [ "$3" = 1 ]; then
    cd "$ROOT_DIR/$SUBGRAPH_PATH"
    npm run codegen

    cd "$ROOT_DIR/$SDK_PATH"
    npm run codegen
fi