#!/bin/sh

SHARING_SMART_CONTRACT_PATH="packages/sharing-smart-contract/contracts"
SMART_CONTRACT_PATH="packages/smart-contract/contracts"
SUBGRAPH_PATH="packages/subgraph"
SDK_PATH="packages/sdk"
ROOT_DIR=$(pwd)

# Check for changes in the specific directory
if git diff --cached --name-only | grep --quiet "$SHARING_SMART_CONTRACT_PATH"; then
    echo "Changes detected in sharing-smart-contract/contracts. Refreshing in others subrepo ..."

    cd "$ROOT_DIR/$SHARING_SMART_CONTRACT_PATH"
    npm run compile
    npm run uml

    cd "$ROOT_DIR/$SMART_CONTRACT_PATH"
    npm run compile

    cd "$ROOT_DIR/$SUBGRAPH_PATH"
    npm run refresh-abis

    cd "$ROOT_DIR/$SDK_PATH"
    npm run refresh-abis

    git add "$SDK_PATH/abis"
    git add "$SUBGRAPH_PATH/abis"
fi

if git diff --cached --name-only | grep --quiet "$SMART_CONTRACT_PATH"; then
    echo "Changes detected in smart-contract/contracts. Refreshing in others subrepo ..."

    cd "$ROOT_DIR/$SMART_CONTRACT_PATH"
    npm run compile

    cd "$ROOT_DIR/$SUBGRAPH_PATH"
    npm run refresh-abis

    cd "$ROOT_DIR/$SDK_PATH"
    npm run refresh-abis

    git add "$SDK_PATH/abis"
    git add "$SUBGRAPH_PATH/abis"
fi