#!/bin/sh

CHECK_DIRECTORY="packages/sharing-smart-contract/contracts"

# Check for changes in the specific directory
if git diff --cached --name-only | grep --quiet "$CHECK_DIRECTORY"; then
    echo "Changes detected in sharing-smart-contract/contracts. Refreshing in others monorepo ..."

    cd packages/sharing-smart-contract
    npm run compile
    npm run uml

    cd ../smart-contract
    npm run compile

    cd ../subgraph
    npm run refresh-abis
    npm run codegen

    cd ../sdk
    npm run refresh-abis
    npm run codegen

else
    echo "No changes in $CHECK_DIRECTORY"
fi

exit 1
