#!/bin/sh

SHARING_SMART_CONTRACT_PATH="packages/sharing-smart-contract/contracts"
SMART_CONTRACT_PATH="packages/sharing-smart-contract/contracts"
SDK_PATH="packages/sdk"
ROOT_DIR=$(pwd)

# Check for changes in the specific directory
if git diff --cached --name-only | grep --quiet "$SHARING_SMART_CONTRACT_PATH"; then
    echo "Changes detected in sharing-smart-contract/contracts. Refreshing in others monorepo ..."

    cd packages/sharing-smart-contract
    npm run compile
    npm run uml

    cd ../smart-contract
    npm run compile

    cd ../subgraph
    npm run refresh-abis
    npm run codegen

    cd ../sdk
    npm run refresh-abis
    npm run codegen
fi

if git diff --cached --name-only | grep --quiet "$SMART_CONTRACT_PATH"; then
    echo "Changes detected in smart-contract/contracts. Refreshing in others monorepo ..."

    cd "$ROOT_DIR/packages/smart-contract"
    npm run compile

    cd ../subgraph
    npm run refresh-abis
    npm run codegen

    cd ../sdk
    npm run refresh-abis
    npm run codegen
fi

if git diff --cached --name-only | grep --quiet "$SDK_PATH"; then
    echo "Changes detected in sdk. Executing specific tasks ..."

    cd "$ROOT_DIR/packages/sdk"
    npm run check-format
    npm run lint
    npm run check-types
fi