name: Smart Contract Deploy

on:
  workflow_dispatch: # Manual trigger
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - avalancheFujiTestnet
          - arbitrumSepolia
          - arbitrum
          - bellecour
        default: 'hardhat'
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

concurrency:
  group: ${{ github.ref }}-core-smart-contract-ci
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/core-smart-contract-ci.yml
    with:
      node-version: 20

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: write # Required to commit deployment files.
    environment: ${{ inputs.network }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'packages/smart-contract'

      - name: Install dependencies
        working-directory: packages/smart-contract
        run: npm ci

      - name: Validate deployment environment and prepare variables
        if: inputs.network != 'hardhat'
        run: |
          NETWORK="${{ inputs.network }}"
          ENVIRONMENT="${{ inputs.environment }}"
          CHAIN_ID="${{ vars.CHAIN_ID }}"
          
          # Define mainnet networks
          MAINNET_NETWORKS=("arbitrum" "bellecour")
          
          IS_MAINNET=false
          for mainnet in "${MAINNET_NETWORKS[@]}"; do
            if [ "$NETWORK" = "$mainnet" ]; then
              IS_MAINNET=true
              break
            fi
          done
          
          # For mainnet networks, check that environment is not dev
          if [ "$IS_MAINNET" = true ] && [ "$ENVIRONMENT" = "dev" ]; then
            echo "Error: Cannot deploy to mainnet ($NETWORK) with dev environment"
            exit 1
          fi
          
          ORIGINAL_FOLDER_NAME="chain-${CHAIN_ID}"
          if [ "$IS_MAINNET" = false ]; then
            NEW_FOLDER_NAME="chain-${CHAIN_ID}-${ENVIRONMENT}"
          else
            NEW_FOLDER_NAME="chain-${CHAIN_ID}"
          fi
          
          # Export variables for subsequent steps
          echo "IS_MAINNET=$IS_MAINNET" >> $GITHUB_ENV
          echo "ORIGINAL_FOLDER_NAME=$ORIGINAL_FOLDER_NAME" >> $GITHUB_ENV
          echo "NEW_FOLDER_NAME=$NEW_FOLDER_NAME" >> $GITHUB_ENV

      - name: Deploy contract
        working-directory: packages/smart-contract
        env:
          # For Deployment
          RPC_URL: ${{ secrets.RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          DATASET_REGISTRY_ADDRESS: ${{ vars.DATASET_REGISTRY_ADDRESS }}
          # For Verification
          EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}
          IS_VERIFICATION_API_V2: ${{ vars.IS_VERIFICATION_API_V2 }}
        run: npm run deploy -- --network ${{ inputs.network }} --deployment-id ${{ inputs.network }} --verify

      - name: Rename deployment folder based on environment
        if: inputs.network != 'hardhat'
        working-directory: packages/smart-contract
        run: |
          # Rename deployment folder if it's a testnet
          if [ "$IS_MAINNET" = false ]; then
            if [ -d "ignition/deployments/$ORIGINAL_FOLDER_NAME" ]; then
              mv "ignition/deployments/$ORIGINAL_FOLDER_NAME" "ignition/deployments/$NEW_FOLDER_NAME"
              echo "Renamed deployment folder from '$ORIGINAL_FOLDER_NAME' to '$NEW_FOLDER_NAME'"
            else
              echo "Warning: Expected deployment folder '$ORIGINAL_FOLDER_NAME' not found"
              ls -la ignition/deployments/ || echo "No deployments folder found"
            fi
          else
            echo "Mainnet deployment: keeping original folder name '$ORIGINAL_FOLDER_NAME'"
          fi
      - name: Save deployment artifacts
        if: inputs.network != 'hardhat'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: save deployment artifacts for ${{ inputs.network }} ${{ inputs.environment }} (${{ github.run_id }})'
          file_pattern: 'packages/smart-contract/ignition/deployments/*'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>'
