name: Smart Contract Deploy

on:
  workflow_dispatch: # Manual trigger
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - avalancheFujiTestnet
          - arbitrumSepolia
          - arbitrum
          - bellecour
        default: 'hardhat'

concurrency:
  group: ${{ github.ref }}-core-smart-contract-ci
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/core-smart-contract-ci.yml
    with:
      node-version: 20

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: write # Required to commit deployment files.
    environment: ${{ inputs.network }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'packages/smart-contract'

      - name: Install dependencies
        working-directory: packages/smart-contract
        run: npm ci

      - name: Deploy contract
        working-directory: packages/smart-contract
        env:
          # For Deployment
          RPC_URL: ${{ secrets.RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          DATASET_REGISTRY_ADDRESS: ${{ vars.DATASET_REGISTRY_ADDRESS }}
          # For Verification
          EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}
          IS_VERIFICATION_API_V2: ${{ vars.IS_VERIFICATION_API_V2 }}
        run: npm run deploy -- --network ${{ inputs.network }} --deployment-id ${{ inputs.network }} --verify

      - name: Save deployment artifacts
        if: inputs.network != 'hardhat'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: save deployment artifacts for ${{ inputs.network }} (${{ github.run_id }})'
          file_pattern: 'packages/smart-contract/ignition/deployments/*'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>'
