name: Test Docker Image

on:
  pull_request:
    branches:
      - '*' # Trigger on any pull request
    paths:
      - 'packages/protected-data-delivery-dapp/**' # Trigger only when changes are made to the dapp

jobs:
  build-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@fix/docker/types
    with:
      image-name: 'protected-data-delivery-dapp'
      image-tag: ${{ github.sha }}
      push: false
      dockerfile: 'packages/protected-data-delivery-dapp/Dockerfile'
