name: Deploy Subgraph - on self-hosted node

on:
  workflow_dispatch: # Triggered manually but we can also trigger with an release event
    inputs:
      environment:
        description: 'Deployment environment (must match a GitHub Environment name)'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - tmp
          - prod

jobs:
  build-and-test:
    uses: ./.github/workflows/subgraph-ci.yml
    with:
      node-version: 20

  deploy:
    needs: build-and-test
    runs-on:
      group: Azure_runners
      labels: [ self-hosted, Linux, X64 ]
    # Associate the job with a GitHub Environment which has pre-defined variables and secrets.
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/subgraph'

      - name: Install dependencies
        working-directory: packages/subgraph
        run: npm ci

      - name: Set Version Label
        working-directory: packages/subgraph
        id: set_version
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "version=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            version=$(npm pkg get version | sed 's/"//g')
            echo "version=$version" >> $GITHUB_OUTPUT
          fi

      - name: Deploy Subgraph
        working-directory: packages/subgraph
        env:
          NETWORK_NAME: bellecour
          VERSION_LABEL: ${{ steps.set_version.outputs.version }}
          GRAPHNODE_URL: ${{ vars.GRAPHNODE_URL }}
          IPFS_URL: ${{ vars.IPFS_URL }}
          DEPLOY_ENV: ${{ vars.ENV_NAME }}
        run: |
          echo "Starting deployment with the following parameters:"
          echo "  Network Name: $NETWORK_NAME"
          echo "  Version Label: $VERSION_LABEL"
          echo "  DEPLOY_ENV: $DEPLOY_ENV"
          echo "  GRAPHNODE_URL: $GRAPHNODE_URL"
          echo "  IPFS_URL: $IPFS_URL"
          npm run all
        shell: bash
