name: Publish Package NPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag to publish (latest or nightly)'
        required: true
        type: choice
        options:
          - latest
          - nightly
        default: nightly

jobs:
  publish-npm:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@feat/publish-npm
    with:
      scope: '@iexec/dataprotector-sdk'
      registry: 'https://registry.npmjs.org'
      node-version: '18'
      environment: ${{ github.event.inputs.target }}
      working-directory: packages/sdk
      tag: ${{ github.event.inputs.tag }}
      install-command: |
        npm ci
        npm run codegen
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
