name: Publish Package NPM

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Select deployment target'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - prod

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sdk
    steps:
      - uses: actions/checkout@v4

      - name: Call reusable workflow from root of subdirectory
        uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.2.0
        with:
          scope: '@iexec/dataprotector-sdk'
          registry: 'https://registry.npmjs.org'
          node-version: '18'
          environment: ${{ github.event.inputs.target }}
        secrets:
          npm-token: ${{ secrets.NPM_TOKEN }}
