name: Publish Package NPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag to publish (latest or nightly)'
        required: true
        type: choice
        options:
          - latest
          - nightly
        default: nightly

jobs:
  publish-npm:
    needs: set-env
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@feat/publish-npm
    with:
      scope: '@iexec/deserializer'
      registry: 'https://registry.npmjs.org'
      node-version: '18'
      tag: ${{ github.event.inputs.tag }}
      install-command: 'npm ci && npm run test:prepare'
      environment: ${{ needs.set-env.outputs.resolved-environment }} # For secrets env
      working-directory: "packages/dataprotector-deserializer"
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
