name: docker workflow for dataprotector subgraph deployer

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (the docker image will not be published)'
        default: false
        type: boolean
      tag:
        description: 'Tag of Docker Image'
        default: 'latest'
        type: string
    secrets:
      docker-username:
        description: 'Docker Hub username (used to log in to Docker Hub and to push the image)'
        required: true
      docker-password:
        description: 'Docker Hub password or PAT (used to log in to Docker Hub and to push the image)'
        required: true

jobs:
  docker-publish:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v3.5.1
    with:
      image-name: 'iexechub/dataprotector-subgraph-deployer'
      registry: 'docker.io'
      dockerfile: 'packages/subgraph/deployer.Dockerfile'
      context: 'packages/subgraph'
      security-scan: true
      security-report: 'sarif'
      hadolint: true
      push: ${{ !inputs.dry-run }}
      image-tag: ${{ inputs.tag }}
    secrets:
      dockerhub-username: ${{ secrets.docker-username }}
      dockerhub-password: ${{ secrets.docker-password }}
      username: ${{ secrets.docker-username }}
      password: ${{ secrets.docker-password }}
