# ⚠️ THIS WORKFLOW IS THE TRUSTED PUBLISHER CONFIGURED ON NPMJS.COM, DO NOT RENAME OR DELETE THIS FILE ⚠️name: SDK - Publish NPM

on:
  # For staging releases
  workflow_dispatch:
  # For latest releases
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  packages: write
  contents: read

jobs:
  set-staging-version:
    # Only run for manual dispatch on main branch
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set publish version
        id: set-staging-version
        working-directory: packages/sdk
        run: |
          CURRENT_VERSION=$(npm pkg get version | tr -d '"')
          NIGHTLY_VERSION="${CURRENT_VERSION}-nightly-${GITHUB_SHA::7}"
          echo "VERSION=${NIGHTLY_VERSION}" >> $GITHUB_OUTPUT
    outputs:
      VERSION: ${{ steps.set-staging-version.outputs.VERSION }}

  publish-npm-staging:
    # Only run for manual dispatch on main branch
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.6.0
    needs: set-staging-version
    with:
      scope: '@iexec/dataprotector'
      registry: 'https://registry.npmjs.org'
      node-version: '18'
      environment: 'staging'
      working-directory: packages/sdk
      tag: 'nightly'
      version: ${{ needs.set-staging-version.outputs.VERSION }}
      install-command: |
        npm ci
        npm run codegen

  publish-npm-latest:
    # # Only run for release published with tag "dataprotector-v*"
    if: ${{ github.event_name == 'release' && startsWith(github.ref_name,'dataprotector-v') }}
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.6.0
    with:
      scope: '@iexec/dataprotector'
      registry: 'https://registry.npmjs.org'
      node-version: '18'
      working-directory: packages/sdk
      tag: 'latest'
      install-command: |
        npm ci
        npm run codegen
