name: Sharing Smart Contract - CI

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'packages/sharing-smart-contract/**'

concurrency:
  group: ${{ github.ref }}-sharing-smart-contract-ci
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/sharing-smart-contracts-reusable.yml
    with:
      node-version: 18
