name: Sharing Smart Contract - CI

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'packages/sharing-smart-contract/**'

concurrency:
  group: ${{ github.ref }}-sharing-smart-contract-ci
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sharing-smart-contract-common
        with:
          node-version: '18'
