name: Sharing Smart Contract - Deploy

on:
  workflow_dispatch: # Manual trigger
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - avalancheFujiTestnet
          - arbitrumSepolia
          - arbitrum
          - bellecour
        default: 'hardhat'
      stage:
        description: 'Deployment stage'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

jobs:
  build-and-test:
    uses: ./.github/workflows/sharing-smart-contracts-ci.yml
    with:
      node-version: 20

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: ${{ inputs.network }}
    permissions:
      contents: write # Required to commit deployment files.
    env:
      CI: true
      # For commit action
      COMMIT_MESSAGE: 'chore: Save deployment artifacts for ${{ inputs.network }} ${{ inputs.stage }} (${{ github.run_id }})'
      GHA_BOT_NAME: 'GitHub Actions Bot'
      GHA_BOT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
      # commit_author: 'GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>'

    steps:
      - name: Validate deployment environment
        if: inputs.network != 'hardhat'
        env:
          NETWORK: ${{ inputs.network }}
          STAGE: ${{ inputs.stage }}
        run: |
          DEPLOYMENT_ID=""
          case "$NETWORK" in
            arbitrum|bellecour)
              if [ "$STAGE" = "dev" ]; then
                echo "Error: Cannot use 'dev' stage with mainnet ($NETWORK)"
                exit 1
              fi
              # Use <network> as deployment id for mainnets.
              DEPLOYMENT_ID="${{ inputs.network }}"
              ;;
            *)
              # Use <network>-<stage> as deployment id for testnets.
              DEPLOYMENT_ID="${{ inputs.network }}-${{ inputs.stage }}"
              ;;
          esac
          echo "deployment-id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'packages/sharing-smart-contract'

      - name: Install dependencies
        working-directory: packages/sharing-smart-contract
        run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Deploy contracts
        working-directory: packages/sharing-smart-contract
        env:
          # For Deployment
          RPC_URL: ${{ secrets.RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ADMIN_PRIVATE_KEY: ${{ secrets.DATAPROTECTOR_OWNER_PRIVATEKEY }} # Fix secret name
          POCO_ADDRESS: ${{ vars.POCO_ADDRESS }}
          DATASET_REGISTRY_ADDRESS: ${{ vars.DATASET_REGISTRY_ADDRESS }}
        run: |
            DEPLOYMENT_ID="$DEPLOYMENT_ID" \
              npm run deploy -- --network ${{ inputs.network }}

      - name: Push deployment artifacts to the current branch
        if: inputs.network != 'hardhat' && github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
          file_pattern: 'packages/sharing-smart-contract/ignition/deployments/* packages/sharing-smart-contract/.openzeppelin/*'
          commit_user_name: ${{ env.GHA_BOT_NAME }}
          commit_user_email: ${{ env.GHA_BOT_EMAIL }}
          commit_author: '${{ env.GHA_BOT_NAME }} <${{ env.GHA_BOT_EMAIL }}>'

      # Since `main` branch is protected, create a PR to push deployment files.
      - name: Push deployment artifacts through a pull request
        if: inputs.network != 'hardhat' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: ${{ env.COMMIT_MESSAGE }}
          add-paths: 'packages/sharing-smart-contract/ignition/deployments/* packages/sharing-smart-contract/.openzeppelin/*'
          committer: ${{ env.GHA_BOT_NAME }}
          author: '${{ env.GHA_BOT_NAME }} <${{ env.GHA_BOT_EMAIL }}>'
          branch: chore/save-deployment-artifacts
          title: ${{ env.COMMIT_MESSAGE }}
          body: 'PR created by "Create Pull Request" action.'
          draft: true

      - name: Verify contracts
        if: inputs.network != 'hardhat'
        continue-on-error: true
        working-directory: packages/sharing-smart-contract
        env:
          EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}
          IS_VERIFICATION_API_V2: ${{ vars.IS_VERIFICATION_API_V2 }}
        run: npm run verify -- "$DEPLOYMENT_ID"
