name: Sharing Smart Contract - Deployment

on:
  workflow_dispatch: # Manual trigger
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - avalancheFujiTestnet
          - arbitrumSepolia
          - arbitrum
          - bellecour
        default: 'hardhat'

jobs:
  # Build and test before deploying.
  build-and-test:
    uses: ./.github/workflows/sharing-smart-contracts-ci.yml
    with:
      node-version: 20

  # Deploy and verify contract.
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit deployment files.
    environment: ${{ inputs.network }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        working-directory: packages/sharing-smart-contract
        run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Deploy contracts
        working-directory: packages/sharing-smart-contract
        env:
          # For Deployment
          RPC_URL: ${{ secrets.RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          POCO_ADDRESS: ${{ env.POCO_ADDRESS }}
          DATASET_REGISTRY_ADDRESS: ${{ env.DATASET_REGISTRY_ADDRESS }}
          # For Verification
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: npm run deploy -- --network ${{ inputs.network }} --deployment-id ${{ inputs.network }} --verify

      - name: Save deployment artifacts
        if: inputs.network != 'hardhat'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: save deployment artifacts for ${{ inputs.network }} (${{ inputs.environment }}, ${{ github.run_id }})'
          file_pattern: 'packages/sharing-smart-contract/ignition/deployments/* packages/sharing-smart-contract/.openzeppelin/*'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>'
