import crypto from 'crypto';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { IExecDataProtector } from '@iexec/dataprotector';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import { BELLECOUR_CHAIN_ID } from '../constants';

const inter = Inter({ subsets: ['latin'] });

const callProtectDataCode = `const dataProtector = new IExecDataProtector(window.ethereum);

dataProtector.protectData({
  name: 'test-from-next',
  data: {
    email: 'test-from-next@example.com',
  },
});
`

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [protectedDataAddress, setProtectedDataAddress] = useState('');
  const [errorMessage, setErrorMessage] = useState('');

  const protectData = async () => {
    setErrorMessage('');
    setProtectedDataAddress('');

    if (!window.ethereum) {
      setErrorMessage('Missing Ethereum provider. Please install Metamask.');
      return;
    }

    const accounts = await window.ethereum.request({
      method: 'eth_requestAccounts',
    });

    // @ts-ignore
    const userAddress = accounts?.[0];

    if (!userAddress) {
      setErrorMessage('Missing user address?');
      return;
    }

    const chainId = await window.ethereum.request({ method: 'eth_chainId' });
    if (Number(chainId) !== BELLECOUR_CHAIN_ID) {
      setErrorMessage('Invalid network, please switch to Bellecour network.');
      return;
    }

    setIsLoading(true);

    const dataProtector = new IExecDataProtector(window.ethereum);
    dataProtector
      .protectDataObservable({
        name: 'test-from-next',
        data: {
          email: 'test-from-next@example.com',
        },
      })
      .subscribe(
        (data) => {
          console.log(data);
          if (data.message === 'PROTECTED_DATA_DEPLOYMENT_SUCCESS') {
            setProtectedDataAddress(data.address);
          }
        },
        (e) => {
          console.log(e);
          setErrorMessage(e.message)
          setIsLoading(false);
        },
        () => {
          console.log('DONE');
          setIsLoading(false);
        }
      );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div>
          Protect an email address:
          <div
            style={{ fontSize: '12px', paddingLeft: '2px', marginTop: '8px' }}
          >
            Open the console to see logs
          </div>

          <div className={styles.codeBlock}>
            <pre>
              <code>
                {callProtectDataCode}
              </code>
            </pre>
          </div>

          <button
            type="button"
            disabled={isLoading}
            style={{ marginTop: '30px' }}
            onClick={protectData}
          >
            Create protected data
          </button>
        </div>

        <div style={{ width: '100%', textAlign: 'center' }}>
          {errorMessage && (
            <div style={{ marginTop: '20px', color: 'red' }}>
              {errorMessage}
            </div>
          )}

          {protectedDataAddress && (
            <div style={{ marginTop: '20px' }}>
              <div>
                Protected data address: <pre
                style={{ display: 'inline-block' }}><code>{protectedDataAddress}</code></pre>
              </div>
              <div style={{ marginTop: '12px' }}>
                See in explorer: <a
                href={`https://explorer.iex.ec/bellecour/dataset/${protectedDataAddress}`}
                target="_blank" rel="noreferrer" style={{
                textDecoration: 'underline',
                fontSize: '14px'
              }}>https://bellecour.iex.ec/address/{protectedDataAddress}</a>
              </div>
            </div>
          )}
        </div>
      </main>
    </>
);
}
